### PR TITLE
Add simple ccorr method to FourierTools

### PR DESCRIPTION
**Pull request by roflmaostc**

### CODE REVIEW

**Comment by roflmaostc** [comment]
@RainerHeintzmann @LukasHasf a simple `ccorr` method first.

We can also add more advanced one like `plan_ccorr` later

**Comment by RainerHeintzmann** [comment]
Thanks for starting this branch! 
Since correlation is really just adding a `conj.` to one of the arrays in Fourier space and we would ideally want all the convolution specializations to also exist as correlations, I would suggest to implement this optional `conj.` as a named argument within the `conv` method. This would keep code replication at a minimum at a minimal combinatorial explosion overhead. The various `corr` methods should still be in a separate file, but only call the `conv` methods with the named argument `correlate=true`. They could use smart argument forwarding, which should be easy to maintain.

**Comment by roflmaostc** [comment]
Yes it is but the final `fftshift` is for example not included and not needed in `conv` hence you only replace 1 line with a call to a different function.

**Comment by RainerHeintzmann** [comment]
Maybe I am missing something here, but should not `corr` and `conv` have the same options of applying final Fourier shifts or not? I would think that there is no fundamental difference between the two except for the `conj.` operation.

**Comment by roflmaostc** [comment]
There kind of is:
```
julia> conv(x,y) = irfft(rfft(x) .* rfft(y), size(x,1))
conv (generic function with 2 methods)

julia> conv([1,2,3,4,5],[1,0,0,0,0])
5-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0
 5.0

julia> ccorr(x,y) = irfft(rfft(x) .* conj.(rfft(y)), size(x,1))
ccorr (generic function with 1 method)

julia> ccorr([1,2,3,4,5],[1,2,3,4,5])
5-element Vector{Float64}:
 55.0
 45.0
 40.0
 40.0
 45.0
```

The conv is oriented the same as the image, the ccorr is centered around the first entry.

**Comment by RainerHeintzmann** [comment]
thanks for the example. However, I think this is what to expect. If the "zero" is in the top left corner and you are correlating two equal array, than the result is zero shift, which has a maximum at zero, i.e. the top left corner. Moving this to the middle seems inconsistent to me.

**Comment by roflmaostc** [comment]
Yes, I agree.
That's why there is a `centered`Bool if you Want to have it shifted

**Pull request merged**
